In [1]:
import numpy as np

# basics

In [11]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [4]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# получить размерность
a.ndim, b.ndim

(1, 2)

In [8]:
b.shape

(2, 3)

In [12]:
a.dtype

dtype('int16')

In [14]:
#размер элемента
a.itemsize

2

In [17]:
#общий размер файла
b.size * b.itemsize, b.nbytes

(24, 24)

# Как получить доступ к элементам, строкам, столбцам

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
# получить конкретный элемент
a[1,2]

10

In [26]:
# получить строку [startindex:endindex:stepsize]
a[0, 1:5]

array([2, 3, 4, 5])

In [27]:
# получить столбец
a[:, 2]

array([ 3, 10])

In [30]:
a[0 , 1:-1:2]

array([2, 4, 6])

In [35]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9 20 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [36]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
c[0,1,1]

4

In [38]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [48]:
c[:,:,0] = [[2,2], [5,6]]
c

array([[[2, 2],
        [2, 4]],

       [[5, 6],
        [6, 8]]])

# Инициализация разных типов массивов

In [51]:
# все нули
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [53]:
# все единицы
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [56]:
# другие числа
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [59]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [63]:
# случайный массивы
np.random.rand(4,2)

array([[0.29118539, 0.98458256],
       [0.63242973, 0.10447416],
       [0.04430174, 0.96469699],
       [0.8811823 , 0.02003515]])

In [65]:
np.random.randint(1,10,(3,3))

array([[4, 7, 5],
       [4, 6, 3],
       [9, 3, 4]])

In [67]:
# матрица идентичности
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
# практика
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Осторожнее с копированием массивов


In [78]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [79]:
b[0] = 100
b,a

(array([100,   2,   3]), array([100,   2,   3]))

In [80]:
c = a.copy()
c[0] = 200
c,a

(array([200,   2,   3]), array([100,   2,   3]))

# математика


In [93]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [95]:
a+=2
a

array([5, 6, 7, 8])

In [83]:
a-2

array([-1,  0,  1,  2])

In [84]:
a*2

array([2, 4, 6, 8])

In [85]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [96]:
b = np.array([1,0,1,0])
a+b

array([6, 6, 8, 8])

In [97]:
a**2

array([25, 36, 49, 64], dtype=int32)

In [98]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [99]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])