Основа numpy - это массив ndarray, это быстрый и гибкий контейнер для хранения N-мерных массивов. Массивы позволяют выполнять математические операции над большими блоками данных. 

**shape** - кортеж, описывающий размеры по каждому измерению (y,x,z)
**dtype** - объект, описывающий тип данных в массиве
**ndim** - количество измерений массива
**tolist** - конвертация в list

Массивы быстрее, требуют меньше памяти, требуют однородности данных

In [1]:
import numpy as np

In [2]:
data = [1, 2, 3, 4, 5]
arr = np.array(data) 

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
(5,)
int32
1


**Типы данных Numpy**
* int64
* float32
* complex
* bool
* object
* string
* unicode

In [3]:
arr2 = arr.astype(np.float64)
arr2

array([1., 2., 3., 4., 5.])

In [4]:
arr3 = np.arange(0, 15, 1.5)
arr3

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

In [5]:
arr4 = np.linspace(0,2,6)
arr4

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [6]:
arr5 = np.random.random_sample(5)
arr5

array([0.82266226, 0.17462261, 0.24473126, 0.04504242, 0.26574414])

##### Диапазон случайных чисел от [a,b]: (b-a)*np.random() + a, где b>a

In [7]:
random_arr = (10 - 5) * np.random.random_sample() + 5
random_arr

5.837171279862062

Операции

In [8]:
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))
print(np.exp(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [9]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
print(a+b)
print(a*b)
print(a/b)
print(a**2)
print(b*3)

[ 4  6  8 10 12]
[ 3  8 15 24 35]
[0.33333333 0.5        0.6        0.66666667 0.71428571]
[ 1  4  9 16 25]
[ 9 12 15 18 21]


Функции агрегаты

In [10]:
arr = np.random.randint(-5, 10, 10)
arr

array([ 9,  6,  6,  8,  4,  2,  3,  7, -3, -3])

In [11]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.sum())
print(arr.std()) # стандартное отклонение
print(np.median(arr))
print(arr < 2)

9
-3
3.9
39
4.011234224026317
5.0
[False False False False False False False False  True  True]


**Манипуляции с массивами**

In [23]:
arr = np.insert(arr, 2, 20)
arr


array([ 9,  6, 20, 20, 20,  6,  8,  4,  2,  3,  7, -3])

In [24]:
arr = np.delete(arr, -1)

In [25]:
arr

array([ 9,  6, 20, 20, 20,  6,  8,  4,  2,  3,  7])

In [27]:
arr.sort()
arr

array([ 2,  3,  4,  6,  6,  7,  8,  9, 20, 20, 20])

In [31]:
arr2 = np.zeros(3, dtype="int32")
arr2

dtype('int32')

In [34]:
arr3 = np.concatenate((arr, arr2))
arr3

array([ 2,  3,  4,  6,  6,  7,  8,  9, 20, 20, 20,  0,  0,  0])

In [35]:
np.array_split(arr3, 6)

[array([2, 3, 4]),
 array([6, 6, 7]),
 array([8, 9]),
 array([20, 20]),
 array([20,  0]),
 array([0, 0])]

# Индексы и одномерные массивы

In [37]:
arr = np.random.randint(-10, 10, 5)
arr

array([ 7, -8,  3, -9, -2])

In [38]:
arr[0] = 0
print(arr[2])
print(arr[0:2])
print(arr[::-1])
print(arr[arr<2])
print(arr[(arr<2) & (arr>0)])
print(arr[(arr>4) | (arr< 0)])
arr[1:4] = 0
print(arr)

3
[ 0 -8]
[-2 -9  3 -8  0]
[ 0 -8 -9 -2]
[]
[-8 -9 -2]
[ 0  0  0  0 -2]


# Матрицы и многомерные массивы

In [43]:
matrix = np.array([(1,2,3), (4,5,6)])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
matrix_3d = np.array([(1,2,3), (4,5,6), (7,8,9)])
matrix_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a_3d_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
a_3d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
print(matrix_3d.shape, matrix_3d.ndim, matrix_3d.size)

(3, 3) 2 9


In [47]:
matrix_3d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
np.insert(matrix,-1, [10,11,12])

array([ 1,  2,  3,  4,  5, 10, 11, 12,  6])

In [55]:
matrix2 = np.random.random((2,2))
matrix2

array([[0.48047058, 0.88189266],
       [0.93130956, 0.26216912]])

In [56]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.resize(matrix, (2,2))

array([[1, 2],
       [3, 4]])

In [59]:
nexw_matrix = np.arange(16).reshape(2,8)
nexw_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

# Создание специальных матриц

In [60]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [75]:
nines = np.full((3,3), 9)
nines

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [68]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Операции над матрицами

In [76]:
print(matrix)
print(nexw_matrix)
print(matrix_3d)
print(matrix2)
print(nines)

[[1 2 3]
 [4 5 6]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.48047058 0.88189266]
 [0.93130956 0.26216912]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [77]:
matrix_3d + nines

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [79]:
matrix_3d * nines

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [80]:
nines / matrix_3d

array([[9.        , 4.5       , 3.        ],
       [2.25      , 1.8       , 1.5       ],
       [1.28571429, 1.125     , 1.        ]])

In [81]:
matrix_3d.dot(nines)

array([[ 54,  54,  54],
       [135, 135, 135],
       [216, 216, 216]])

In [82]:
np.delete(matrix_3d, 1, axis = 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [83]:
np.delete(matrix_3d, 1, axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [84]:
np.sin(matrix_3d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [85]:
np.log(matrix_3d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [86]:
matrix.sum()

21

In [87]:
print(matrix_3d.max())
print(matrix_3d.max(axis=0))

9
[7 8 9]


In [88]:
np.mean(matrix, axis=0)

array([2.5, 3.5, 4.5])

In [89]:
matrix ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [91]:
np.concatenate((matrix_3d, nines), axis=1)

array([[1, 2, 3, 9, 9, 9],
       [4, 5, 6, 9, 9, 9],
       [7, 8, 9, 9, 9, 9]])

In [92]:
np.hstack((matrix_3d, nines))

array([[1, 2, 3, 9, 9, 9],
       [4, 5, 6, 9, 9, 9],
       [7, 8, 9, 9, 9, 9]])

In [93]:
np.vstack((matrix_3d, nines))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [94]:
np.split(matrix_3d, 3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [95]:
np.append(matrix_3d, np.array([10,11,12]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Индексация

In [96]:
matrix = matrix_3d
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
matrix[1,2]

6

In [98]:
matrix[2] #row

array([7, 8, 9])

In [99]:
matrix[:,2] # column

array([3, 6, 9])

In [100]:
matrix[1:3, 0:2] # 0 и 1 столбец, 1 и 2 строки

array([[4, 5],
       [7, 8]])

In [101]:
matrix[matrix>2]

array([3, 4, 5, 6, 7, 8, 9])

In [102]:
matrix.T #транспонированная - столбцы и строки меняются местами


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [103]:
matrix.flatten() # в массив

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.linalg.inv(matrix) # обратная матрица

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [105]:
np.trace(matrix) # след матрицы

15

In [106]:
np.linalg.det(matrix) # определитель

6.66133814775094e-16

In [107]:
np.linalg.matrix_rank(matrix) # ранк

2

In [110]:
eigenvalues, eifenvectors = np.linalg.eig(matrix) # собственные числа и векторы
print(eigenvalues)
print()
print(eifenvectors)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Дополнительные возможности

In [111]:
np.info(matrix) #np.eye

class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1e7800bb190
byteorder:  little
byteswap:  False
type: int32


In [ ]:
np.loadtxt("file.txt")
np.genfromtxt("file.csv", delimeter="|")
np.savetxt("file.txt", arr, delimeter = " ")
np.savetxt("file.csv", arr, delimeter= "|")